// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6OXyAURsAepxSG31qNX5xGe0u4dqih8',
    appId: '1:986610493805:web:2f78eeabf49a26496b9264',
    messagingSenderId: '986610493805',
    projectId: 'ren-app-ad9a6',
    authDomain: 'ren-app-ad9a6.firebaseapp.com',
    storageBucket: 'ren-app-ad9a6.appspot.com',
    measurementId: 'G-VE6ZRNJMJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQmwrLvRpqwAsms-eN3E6N6gY2L08CqY',
    appId: '1:986610493805:android:e23ab503934455816b9264',
    messagingSenderId: '986610493805',
    projectId: 'ren-app-ad9a6',
    storageBucket: 'ren-app-ad9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QghZijtZ_aPSWJ66OjzvsS5zJ2_Ryjo',
    appId: '1:986610493805:ios:b1f2330399501bb76b9264',
    messagingSenderId: '986610493805',
    projectId: 'ren-app-ad9a6',
    storageBucket: 'ren-app-ad9a6.appspot.com',
    iosClientId: '986610493805-k3gkj7vk0ki27l37j4b1sbubd0b52eit.apps.googleusercontent.com',
    iosBundleId: 'com.example.ren',
  );
}
